### ISSUE TITLE
看版娘对话框太长问题

### ISSUE THREAD

**Issue by ppap6664180** [Dreamer-Paul/Pio#24]
### 2. 正常情况下的结果如何，你看到的呢？
点击看版娘互动的对话框长度太长

### 3. 服务器的运行环境是？

- 操作系统版本：
- Apache版本：2.4
- PHP 版本：2.4
- 插件版本：7.4.5
- 浏览器版本：

[//]: # (如有图片请附上截图)
![微信图片_20210724113123](https://user-images.githubusercontent.com/52909556/126856236-73b9de9b-70c4-435f-8e03-2e5f468da678.png)

**Comment by YexuanXiao** [comment]
蹲一个网页壁纸🥰

**Comment by Dreamer-Paul** [comment]
估计是 CSS 冲突，被主题的全局样式覆盖了，方便提供下链接么

**Comment by ppap6664180** [comment]
> 估计是 CSS 冲突，被主题的全局样式覆盖了，方便提供下链接么

我只是在本机操作 没有服务器及域名

**Comment by ppap6664180** [comment]
> 蹲一个网页壁纸🥰

使用的是[Cuckoo 双栏模板](https://typecho.me/1347.html)

**Comment by Dreamer-Paul** [comment]
```css
.left {
    width: 700px;
    float: left
}

.page-img {
    background: center center no-repeat;
    height: 250px;
    background-size: cover
}

.right {
    width: 320px;
    float: right;
    margin-bottom: 20px
}
```

主题样式写的不严谨，很容易和第三方插件产生冲突，建议更换主题解决

要么直接给对应主题作者提 Issues，一个正经的主题开发不可能用这个随性的命名的，还是全局作用域...
